//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPS410_CampusBikeRental.Code
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bike
    {
        public int bikeNumber { get; set; }
        public Nullable<bool> isAvailable { get; set; }
        public string condition { get; set; }
        public string location { get; set; }
    }
}
