//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPS410_CampusBikeRental.Code
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bike_Condition
    {
        public string Condition { get; set; }
        public int Code { get; set; }
    }
}
