//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPS410_CampusBikeRental.Code
{
    using System;
    using System.Collections.Generic;
    
    public partial class Checkout
    {
        public int checkoutId { get; set; }
        public string username { get; set; }
        public int bikeNumber { get; set; }
        public Nullable<System.DateTime> checkOut1 { get; set; }
        public Nullable<System.DateTime> checkIn { get; set; }
        public Nullable<System.DateTime> scheduledOutDate { get; set; }
        public Nullable<System.DateTime> scheduledOutTime { get; set; }
        public Nullable<System.DateTime> scheduledInDate { get; set; }
        public Nullable<System.DateTime> scheduledInTime { get; set; }
        public string location { get; set; }
        public Nullable<bool> cancelledReservation { get; set; }
    }
}
